AWSTemplateFormatVersion: '2010-09-09'
Description: OpenBTPS Static Site

Parameters:
  BucketName:
    Type: String
    Description: OpenBTPS Static Documentation site

Resources:
  OpenBTPSDocsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false

  PublicReadPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref OpenBTPSDocsBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${BucketName}/*'

Outputs:
  WebsiteURL:
    Description: Public website URL
    Value: !Sub 'http://${BucketName}.s3-website-${AWS::Region}.amazonaws.com'
